name: CI/CD Workflow for GeoPortal

on:
  pull_request:
    branches:
      - main # Trigger CI on pull requests targeting the main branch
  push:
    branches:
      - main # Trigger CD on push to the main branch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

  build-and-deploy:
    needs: ci # Ensure deploy only after CI success
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e  # Exit on any error
            source ~/.bashrc || source ~/.profile
            cd /home/***/var/www/geoportal/geoportal-webapp

            # Check for conflicts in pnpm-lock.yaml and resolve them
            if git diff --name-only --diff-filter=U | grep -q "pnpm-lock.yaml"; then
              echo "pnpm-lock.yaml has unresolved conflicts. Attempting to resolve."
              git merge --abort || true
              git reset --hard HEAD
            fi

            # Stash all changes including pnpm-lock.yaml
            git stash push -m "Stash local changes"

            # Force pull changes from main
            git fetch origin main
            git reset --hard origin/main

            # Apply stashed changes
            git stash pop

            # Check for conflicts again and resolve them
            if git diff --name-only --diff-filter=U | grep -q "pnpm-lock.yaml"; then
              echo "pnpm-lock.yaml has unresolved conflicts. Please resolve them."
              git checkout --theirs pnpm-lock.yaml
              git add pnpm-lock.yaml
              git commit -m "Resolve conflicts in pnpm-lock.yaml"
            fi

            # Ensure the lockfile is up to date
            /home/***/.nvm/versions/node/v18.20.2/bin/pnpm install

            # Build the project
            /home/***/.nvm/versions/node/v18.20.2/bin/pnpm build

            # Use pm2 to manage the process
            /home/***/.nvm/versions/node/v18.20.2/bin/pm2 start /home/***/.nvm/versions/node/v18.20.2/bin/pnpm --name "geoportal" -- start || /home/***/.nvm/versions/node/v18.20.2/bin/pm2 restart geoportal -f
