name: Deploy GeoPortal

on:
  push:
    branches:
      - main # Replace with your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }} # Use the SSH gateway IP here if that's how you connect
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.SSH_PORT }} # Standard SSH port is 22, but yours is different
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            source ~/.bashrc || source ~/.profile  # Attempt to load the environment
            cd /home/ubuntu/var/www/geoportal/ci-cd-test
            git pull origin main
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/pnpm install --production
